title: Using buttons with Scratch
hero_image: images/banner.png
description: use a button with Scratch Pi GPIO
original_url: 
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: false
interests: ""
technologies: "scratch, raspberry pi"
steps:
  - title: Using a button
